ExternalProject_Add(ArrayFire
  GIT_REPOSITORY "https://github.com/arrayfire/arrayfire.git"
  GIT_TAG "v3.4.2"
  PREFIX deps/ArrayFire
  BUILD_IN_SOURCE
  UPDATE_COMMAND ""
  DEPENDS FFTW_D FFTW_F Boost Lapack
  CMAKE_CACHE_ARGS
    ## CXX should not be needed, but it a cmake default test
    -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
    -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
    -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
    -DBUILD_GRAPHICS:BOOL=OFF
    -DBoost_LIBRARY_DIR:PATH=${Boost_LIBRARY_DIR}
    -DBoost_INCLUDE_DIR:PATH=${Boost_INCLUDE_DIR}
    -DFFTW_USE_STATIC_LIBS:BOOL=ON
    -DFFTW_ROOT:PATH=${FFTW_INSTALL_DIR}
    -DFFTW_LIBRARIES:PATH=${FFTW_INSTALL_DIR}/lib
    -DFFTW_LIB_PATH:PATH=${FFTW_INSTALL_DIR}/lib
    -DFFTW_INCLUDES:PATH=${FFTW_INSTALL_DIR}/include
    -DFFTW_INCLUDE_PATH:PATH=${FFTW_INSTALL_DIR}/include
    -DBUILD_TEST:BOOL=OFF
    -DBUILD_EXAMPLES:BOOL=OFF
    -DUSE_FREEIMAGE_STATIC:BOOL=ON
    -DLAPACK_DIR:PATH=${LAPACK_DIR}
    -DLAPACK_LIBRARIES:PATH=${LAPACK_DIR}/lib/liblapack.a
    -DLAPACK_INCLUDE_DIR:PATH=${LAPACK_DIR}/src/Lapack/LAPACKE/include
  )
