ExternalProject_Add(ArrayFire
  GIT_REPOSITORY "https://github.com/arrayfire/arrayfire.git"
  GIT_TAG "v3.4.2"
  PREFIX deps/ArrayFire
  BUILD_IN_SOURCE
  UPDATE_COMMAND ""
  DEPENDS FFTW Boost
  CMAKE_CACHE_ARGS
    ## CXX should not be needed, but it a cmake default test
    -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
    -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
    -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
    -DBoost_LIBRARY_DIR:PATH=${Boost_LIBRARY_DIR}
    -DBoost_INCLUDE_DIR:PATH=${Boost_INCLUDE_DIR}
    -DFFTW_USE_STATIC_LIBS:BOOL=ON
    -DFFTW_ROOT:PATH=${FFTW_INSTALL_DIR}
    -DBUILD_TEST:BOOL=OFF
    -DBUILD_EXAMPLES:BOOL=OFF
    -DBUILD_GRAPHICS:BOOL=OFF
  )
