ExternalProject_Add(OpenBLAS
  GIT_REPOSITORY "git://github.com/xianyi/OpenBLAS.git"
  GIT_TAG "master"
  PREFIX deps/OpenBLAS
  BUILD_IN_SOURCE 1
  BUILD_COMMAND       ${CMAKE_MAKE_PROGRAM} NO_LAPACK=1 CC=${CMAKE_C_COMPILER} 
  INSTALL_COMMAND     ${CMAKE_MAKE_PROGRAM} install PREFIX=<INSTALL_DIR>
  UPDATE_COMMAND      ""
  CONFIGURE_COMMAND   ""
)
